# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\desing.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 443)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Qwidget = QtWidgets.QWidget(self.centralwidget)
        self.Qwidget.setGeometry(QtCore.QRect(218, 9, 351, 425))
        self.Qwidget.setStyleSheet("")
        self.Qwidget.setObjectName("Qwidget")
        self.label_2 = QtWidgets.QLabel(self.Qwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 60, 40))
        self.label_2.setStyleSheet("font: 12pt \"Cooper Black\";color:#3CB371")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.Qwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 150, 150, 20))
        self.label_6.setStyleSheet("color:#3CB371;\n"
"font: 12pt \"Wide Latin\";\n"
"text-decoration: underline;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Qwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 230, 150, 20))
        self.label_7.setStyleSheet("color:#3CB371;\n"
"font: 12pt \"Wide Latin\";\n"
"text-decoration: underline;")
        self.label_7.setObjectName("label_7")
        self.img_email_login = QtWidgets.QLabel(self.Qwidget)
        self.img_email_login.setGeometry(QtCore.QRect(40, 120, 60, 60))
        self.img_email_login.setStyleSheet("background-image:url(\"email.png\");\n"
"background-size: cover;\n"
"background-repeat: no-repeat;")
        self.img_email_login.setText("")
        self.img_email_login.setObjectName("img_email_login")
        self.img_senha_login = QtWidgets.QLabel(self.Qwidget)
        self.img_senha_login.setGeometry(QtCore.QRect(40, 200, 60, 60))
        self.img_senha_login.setStyleSheet("background-image:url(\"senha.png\");\n"
"background-size: cover;\n"
"background-repeat: no-repeat;")
        self.img_senha_login.setText("")
        self.img_senha_login.setObjectName("img_senha_login")
        self.btn_login = QtWidgets.QPushButton(self.Qwidget)
        self.btn_login.setGeometry(QtCore.QRect(120, 310, 100, 40))
        self.btn_login.setStyleSheet("color:white;\n"
"font: 10pt \"Cooper Black\";\n"
"background:#5F9EA0")
        self.btn_login.setObjectName("btn_login")
        self.Email_login = QtWidgets.QLineEdit(self.Qwidget)
        self.Email_login.setGeometry(QtCore.QRect(100, 144, 150, 21))
        self.Email_login.setStyleSheet("border-radius:5px;\n"
"background:white")
        self.Email_login.setObjectName("Email_login")
        self.Senha_login = QtWidgets.QLineEdit(self.Qwidget)
        self.Senha_login.setGeometry(QtCore.QRect(100, 224, 150, 21))
        self.Senha_login.setStyleSheet("border-radius:5px;\n"
"background:white")
        self.Senha_login.setObjectName("Senha_login")
        self.label_12 = QtWidgets.QLabel(self.Qwidget)
        self.label_12.setGeometry(QtCore.QRect(160, 121, 47, 13))
        self.label_12.setStyleSheet("color:#363636")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Qwidget)
        self.label_13.setGeometry(QtCore.QRect(160, 201, 47, 13))
        self.label_13.setStyleSheet("color:#363636")
        self.label_13.setObjectName("label_13")
        self.Excecoes_login = QtWidgets.QLineEdit(self.Qwidget)
        self.Excecoes_login.setEnabled(True)
        self.Excecoes_login.setGeometry(QtCore.QRect(119, 284, 131, 20))
        self.Excecoes_login.setStyleSheet("border-radius:1px; background-color: transparent;\n"
"")
        self.Excecoes_login.setObjectName("Excecoes_login")
        self.btn_sobre = QtWidgets.QPushButton(self.Qwidget)
        self.btn_sobre.setGeometry(QtCore.QRect(300, 11, 40, 40))
        self.btn_sobre.setStyleSheet("background-image:url(\"info.png\");\n"
"background-size: cover;\n"
"background-repeat: no-repeat;\n"
"border-radius:5px;")
        self.btn_sobre.setText("")
        self.btn_sobre.setIconSize(QtCore.QSize(32, 32))
        self.btn_sobre.setObjectName("btn_sobre")
        self.fundo_login = QtWidgets.QLabel(self.Qwidget)
        self.fundo_login.setGeometry(QtCore.QRect(0, 0, 354, 426))
        self.fundo_login.setObjectName("fundo_login")
        self.fundo_login.raise_()
        self.btn_sobre.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.img_email_login.raise_()
        self.img_senha_login.raise_()
        self.btn_login.raise_()
        self.Email_login.raise_()
        self.Senha_login.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.Excecoes_login.raise_()
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(9, 9, 211, 425))
        self.widget_2.setStyleSheet("background:#363636;\n"
"background-size:cover;")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(50, 30, 110, 40))
        self.label.setStyleSheet("font: 12pt \"Cooper Black\";color:#3CB371")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 105, 140, 20))
        self.label_3.setStyleSheet("color:#3CB371;\n"
"font: 12pt \"Wide Latin\";\n"
"text-decoration: underline;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(60, 170, 140, 20))
        self.label_4.setStyleSheet("color:#3CB371;\n"
"font: 12pt \"Wide Latin\";\n"
"text-decoration: underline;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(60, 240, 140, 20))
        self.label_5.setStyleSheet("color:#3CB371;\n"
"font: 12pt \"Wide Latin\";\n"
"text-decoration: underline;")
        self.label_5.setObjectName("label_5")
        self.btn_cadastrar = QtWidgets.QPushButton(self.widget_2)
        self.btn_cadastrar.setGeometry(QtCore.QRect(60, 310, 100, 40))
        self.btn_cadastrar.setStyleSheet("color:white;\n"
"font: 10pt \"Cooper Black\";\n"
"background:#5F9EA0")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.img_nome = QtWidgets.QLabel(self.widget_2)
        self.img_nome.setGeometry(QtCore.QRect(0, 80, 60, 60))
        self.img_nome.setStyleSheet("background-image:url(\"user.png\");\n"
"background-size: cover;\n"
"background-repeat: no-repeat;")
        self.img_nome.setText("")
        self.img_nome.setObjectName("img_nome")
        self.img_email = QtWidgets.QLabel(self.widget_2)
        self.img_email.setGeometry(QtCore.QRect(0, 150, 60, 60))
        self.img_email.setStyleSheet("background-image:url(\"email.png\");\n"
"background-size: cover;\n"
"background-repeat: no-repeat;")
        self.img_email.setText("")
        self.img_email.setObjectName("img_email")
        self.img_senha = QtWidgets.QLabel(self.widget_2)
        self.img_senha.setGeometry(QtCore.QRect(0, 220, 60, 60))
        self.img_senha.setStyleSheet("background-image:url(\"senha.png\");\n"
"background-size: cover;\n"
"background-repeat: no-repeat;")
        self.img_senha.setText("")
        self.img_senha.setObjectName("img_senha")
        self.Nome_cadastro = QtWidgets.QLineEdit(self.widget_2)
        self.Nome_cadastro.setGeometry(QtCore.QRect(60, 100, 141, 21))
        self.Nome_cadastro.setStyleSheet("border-radius:5px;\n"
"background:white")
        self.Nome_cadastro.setText("")
        self.Nome_cadastro.setObjectName("Nome_cadastro")
        self.Email_cadastro = QtWidgets.QLineEdit(self.widget_2)
        self.Email_cadastro.setGeometry(QtCore.QRect(60, 165, 141, 21))
        self.Email_cadastro.setStyleSheet("border-radius:5px;\n"
"background:white")
        self.Email_cadastro.setObjectName("Email_cadastro")
        self.Senha_cadastro = QtWidgets.QLineEdit(self.widget_2)
        self.Senha_cadastro.setGeometry(QtCore.QRect(60, 235, 141, 21))
        self.Senha_cadastro.setStyleSheet("border-radius:5px;\n"
"background:white")
        self.Senha_cadastro.setObjectName("Senha_cadastro")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(110, 143, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(110, 213, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(110, 79, 47, 13))
        self.label_11.setObjectName("label_11")
        self.Excecoes = QtWidgets.QLineEdit(self.widget_2)
        self.Excecoes.setEnabled(False)
        self.Excecoes.setGeometry(QtCore.QRect(59, 280, 150, 20))
        self.Excecoes.setStyleSheet("border-radius:1px; color:red;")
        self.Excecoes.setObjectName("Excecoes")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Entrar"))
        self.label_2.setText(_translate("MainWindow", "LOGIN"))
        self.label_6.setText(_translate("MainWindow", "_______________________"))
        self.label_7.setText(_translate("MainWindow", "_______________________"))
        self.btn_login.setText(_translate("MainWindow", "➲ ENTRAR"))
        self.label_12.setText(_translate("MainWindow", "E-mail"))
        self.label_13.setText(_translate("MainWindow", "Senha"))
        self.fundo_login.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "CADASTRAR"))
        self.label_3.setText(_translate("MainWindow", "_______________________"))
        self.label_4.setText(_translate("MainWindow", "_______________________"))
        self.label_5.setText(_translate("MainWindow", "_______________________"))
        self.btn_cadastrar.setText(_translate("MainWindow", "FINALIZAR"))
        self.label_9.setText(_translate("MainWindow", "E-mail"))
        self.label_10.setText(_translate("MainWindow", "Senha"))
        self.label_11.setText(_translate("MainWindow", "Nome"))
