# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sobre(object):
    def setupUi(self, Sobre):
        Sobre.setObjectName("Sobre")
        Sobre.resize(408, 285)
        self.centralwidget = QtWidgets.QWidget(Sobre)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 240, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 30, 111, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.linkedin = QtWidgets.QLabel(self.centralwidget)
        self.linkedin.setGeometry(QtCore.QRect(200, 40, 50, 50))
        self.linkedin.setAcceptDrops(True)
        self.linkedin.setStyleSheet("\n"
"background-size:cover;")
        self.linkedin.setText("")
        self.linkedin.setObjectName("linkedin")
        self.github = QtWidgets.QLabel(self.centralwidget)
        self.github.setGeometry(QtCore.QRect(200, 180, 50, 50))
        self.github.setStyleSheet("background-size:cover;")
        self.github.setText("")
        self.github.setObjectName("github")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(56, 7, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.LocalImagem = QtWidgets.QLabel(self.centralwidget)
        self.LocalImagem.setGeometry(QtCore.QRect(20, 29, 147, 196))
        self.LocalImagem.setStyleSheet("background-size:cover;")
        self.LocalImagem.setText("")
        self.LocalImagem.setObjectName("LocalImagem")
        self.btn_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_voltar.setGeometry(QtCore.QRect(340, 220, 64, 64))
        self.btn_voltar.setAcceptDrops(False)
        self.btn_voltar.setStyleSheet("background-size:cover;\n"
"border-radius:15px")
        self.btn_voltar.setText("")
        self.btn_voltar.setIconSize(QtCore.QSize(64, 64))
        self.btn_voltar.setObjectName("btn_voltar")
        self.btn_voltar.clicked.connect(Sobre.close)
        self.fundo_sobre = QtWidgets.QLabel(self.centralwidget)
        self.fundo_sobre.setGeometry(QtCore.QRect(1, 0, 403, 286))
        self.fundo_sobre.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.fundo_sobre.setAcceptDrops(True)
        self.fundo_sobre.setText("")
        self.fundo_sobre.setObjectName("fundo_sobre")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(250, 57, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setStyleSheet("border-radius:1px; background-color: transparent;")
        self.textEdit.setUndoRedoEnabled(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setEnabled(True)
        self.textEdit_2.setGeometry(QtCore.QRect(250, 200, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit_2.setAcceptDrops(False)
        self.textEdit_2.setStyleSheet("border-radius:1px; background-color: transparent;")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(200, 110, 50, 50))
        self.email.setStyleSheet("background-size:cover;")
        self.email.setText("")
        self.email.setObjectName("email")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setEnabled(True)
        self.textEdit_3.setGeometry(QtCore.QRect(250, 129, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit_3.setAcceptDrops(False)
        self.textEdit_3.setStyleSheet("border-radius:1px; background-color: transparent;")
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.fundo_sobre.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.linkedin.raise_()
        self.github.raise_()
        self.label_3.raise_()
        self.LocalImagem.raise_()
        self.btn_voltar.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.label_5.raise_()
        self.email.raise_()
        self.textEdit_3.raise_()
        Sobre.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sobre)
        QtCore.QMetaObject.connectSlotsByName(Sobre)

    def retranslateUi(self, Sobre):
        _translate = QtCore.QCoreApplication.translate
        Sobre.setWindowTitle(_translate("Sobre", "Dev"))
        self.label_2.setText(_translate("Sobre", " Ryan Barbosa Silva"))
        self.label_3.setText(_translate("Sobre", "Desenvolvido por"))
        self.textEdit.setHtml(_translate("Sobre", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ryan Barbosa Silva</p></body></html>"))
        self.textEdit_2.setHtml(_translate("Sobre", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ryanprogrammer</p></body></html>"))
        self.label_5.setText(_translate("Sobre", "em: 17/12/2021"))
        self.textEdit_3.setHtml(_translate("Sobre", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ryprogrammerpy@gmail.com</p></body></html>"))
